Exact plugin
valtimo-platform/valtimo-frontend-libraries pull request #245
Opened 2022-10-17 12:28 UTC by nielserkamp-ritense

2022-10-27 15:20 UTC, maisaritense requested changes

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/exact-refresh-token.ts
> +  accessToken: String;
just to make sure you're using capitalized 'String' intentionally because you want the type to be an object

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/exact-plugin.ts
> +  clientId: String;
just to make sure you're using capitalized 'String' intentionally because you want the type to be an object

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/exact-plugin.module.ts
> +@NgModule({
small suggestion: use prettier to arrange and break into lines

```
@NgModule({
   declarations: [
     ExactGetRequestConfigurationComponent,
     ExactPostRequestConfigurationComponent,
     ExactPutRequestConfigurationComponent,
     ExactPluginConfigurationComponent,
     ExactRedirectComponent,
   ],
```

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-plugin-configuration/exact-plugin-configuration.component.ts
> +import {BehaviorSubject, combineLatest, interval, Observable, Subject, Subscription, take, tap, timer} from 'rxjs';
remove unused imports 
- interval
- Subject
- tap
- timer
- styleUrls: ['./sample-plugin-configuration.component.scss'],

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-plugin-configuration/exact-plugin-configuration.component.ts
> +  onReceiveToken(event) {
add function return type

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-plugin-configuration/exact-plugin-configuration.component.ts
> +  exchangeAuthorizationCode(formValue, code) {
add function return type

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-plugin-configuration/exact-plugin-configuration.component.ts
> +  private storageCallbackFun!: any;
add explicit type

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-plugin-configuration/exact-plugin-configuration.component.html
> +<v-form
- run prettier
- add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-put-request-configuration/exact-put-request-configuration.component.ts
> +import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-put-request-configuration/exact-put-request-configuration.component.ts
> +import ExactPostRequestConfiguration from '../exact-action-post-request-configuration/exact-post-request-configuration';
remove unused import

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-put-request-configuration/exact-put-request-configuration.component.html
> +<v-form
- run prettier
- add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-post-request-configuration/exact-post-request-configuration.component.ts
> +import ExactGetRequestConfiguration from '../exact-action-get-request-configuration/exact-get-request-configuration';
remove unused import

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-post-request-configuration/exact-post-request-configuration.component.ts
> +import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-post-request-configuration/exact-post-request-configuration.component.html
> +<v-form
- run prettier
- add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-get-request-configuration/exact-get-request-configuration.component.ts
> +import {Component, EventEmitter, Input, OnDestroy, OnInit, Output} from '@angular/core';
add **Copyright** text at the beginning of the file

2022-10-27 15:20 UTC, maisaritense commented on projects/valtimo/exact-plugin/src/lib/components/exact-action-get-request-configuration/exact-get-request-configuration.component.html
> +<v-form
- run prettier
- add **Copyright** text at the beginning of the file

2022-10-28 08:04 UTC, nielserkamp-ritense commented
@maisaritense Could you check again please?

2022-11-01 12:52 UTC, Rick-Ritense commented on package.json
> +    "libs:lint:exact-plugin": "ng lint @valtimo/customer"
I think this should be "ng lint @valtimo/exact-plugin"

2022-11-01 13:14 UTC, Rick-Ritense commented
I see you have placed your plugin at `/projects/valtimo/exact-plugin`, all existing plugins are added in `/projects/plugin/src/lib/plugins`. Is there a specific reason you choose another package?

2022-11-01 14:08 UTC, nielserkamp-ritense commented
Nobody told me and it wasn't really explained anywhere

2022-11-01 14:09 UTC, nielserkamp-ritense commented
Adjusted the lint

2022-11-01 15:37 UTC, Rick-Ritense approved these changes

2022-11-02 09:50 UTC, maisaritense approved these changes

2022-11-02 10:43 UTC, merged