Update CaseList and CarbonTable
valtimo-platform/valtimo-frontend-libraries pull request #578
Opened 2023-09-20 14:35 UTC by teodor-ritense

2023-09-21 07:16 UTC, mritense commented
Column titles are not translated

2023-09-21 07:16 UTC, mritense commented
Query params / pagination / assignee filters are not recovered from URL

2023-09-21 07:17 UTC, mritense commented
Arrows don't clear when sorting on another column

2023-09-25 09:02 UTC, teodor-ritense commented
> Column titles are not translated

Updated

2023-09-25 09:02 UTC, teodor-ritense commented
> Query params / pagination / assignee filters are not recovered from URL

Updated

2023-09-25 09:02 UTC, teodor-ritense commented
> Arrows don't clear when sorting on another column

Updated

2023-09-25 09:42 UTC, Klaas-Ritense approved these changes

2023-09-25 09:43 UTC, Klaas-Ritense commented on projects/valtimo/plugin/src/lib/plugins/verzoek/components/verzoek-configuration/verzoek-configuration.component.html
> +  <ng-container *ngIf="{objectManagementSelectItems: objectManagementSelectItems$ | async} as vars">
This has moved to line 144

2023-09-25 09:44 UTC, Klaas-Ritense requested changes
objectManagement has moved

2023-09-25 12:13 UTC, Klaas-Ritense approved these changes

2023-09-25 12:13 UTC, merged