Add add functionality and column list for ZGW
valtimo-platform/valtimo-frontend-libraries pull request #949
Opened 2024-04-23 08:02 UTC by teodor-ritense

[[FE] Document list columns management](https://ritense.tpondemand.com/entity/107913-fe-document-list-columns-management)

PARTIAL FUNCTIONALITY:
- All edit and sorting stuff is pending on another story

PLEASE CHECK TRANSLATIONS

2024-04-25 07:49 UTC, peetritense requested changes

2024-04-25 07:49 UTC, peetritense commented on projects/valtimo/config/assets/core/nl.json
> +      "deleteText": "Weet je zeker dat je dit kolom wilt verwijderen?"
```suggestion
      "deleteText": "Weet je zeker dat je deze kolom wilt verwijderen?"
```

2024-04-25 07:49 UTC, peetritense commented on projects/valtimo/config/assets/core/nl.json
> +      "documentColumns": "Documentkolommen"
```suggestion
      "documentColumns": "Document kolommen"
```

2024-04-25 07:49 UTC, peetritense commented on projects/valtimo/config/assets/core/nl.json
I'm missing the "defaultSort": "Standaard sortering", on line 825 (?)

2024-04-25 07:49 UTC, peetritense commented on projects/valtimo/config/assets/core/de.json
I'm missing the "defaultSort": "Standaard sortering", on line 825 (?)

2024-04-25 07:51 UTC, teodor-ritense commented on projects/valtimo/config/assets/core/nl.json
Will add it when the defaulSorting is available functionality wise

2024-04-25 07:54 UTC, peetritense approved these changes

2024-04-26 09:02 UTC, sofiaIvarsRitense approved these changes

2024-04-26 12:40 UTC, merged